#!usr/bin/python

#
# Chapter 3-27
# Example of a mutation-based random-testing.
# Inputs are generated by modifying, non-randomly generated inputs, like
# pdf, docs, text files? or could it be other stuff? check out..

#
#
############ constants

apps = ["/Applications/LibreOffice.app/Contents/MacOS/soffice.bin"
     ]

file_list = ["test.doc"]

fuzz_output = "./fuzzed.doc"

FuzzFactor = 250
num_tests = 10000
############# code

import math
import random
import string
import subprocess
import time

for i in range(num_tests):
  file_choice = random.choice(file_list)
  app = random.choice(apps)

  buf = bytearray(open(file_choice, 'rb').read())

  numwrites = random.randrange(math.ceil((float(len(buf)) / FuzzFactor)))+1

  for j in range(numwrites):
    rbyte = random.randrange(256)
    rn = random.randrange(len(buf))
    buf[rn] = "%c" % (rbyte)

  open(fuzz_output, 'wb').write(buf)

  print 'call with:'
  print 'app', app
  print 'fuzz_output', fuzz_output
  
  process = subprocess.Popen([app, fuzz_output])

  time.sleep(4)
  crashed = process.poll()

  if not crashed:
    process.terminate()